export const FETCH_DATA_COIN = "FETCH_DATA_COIN";
export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const DELETE_DATA_COIN = "DELETE_DATA_COIN";